### ISSUE TITLE
Oobabooga is removing non-HF ExLlamaV2 loader

### ISSUE THREAD

**Issue by jepjoo** [SoylentMithril/BrainHackingChip#5]
Just a heads up, as BrainHackingChip is dependent on it:

https://github.com/oobabooga/text-generation-webui/pull/5431

**Comment by SoylentMithril** [comment]
Thanks for the heads up! The HF version is a lot more annoying to hook, but I'm looking into it. Hopefully exllamav2 non-HF isn't removed soon.

**Comment by SoylentMithril** [comment]
Exllamav2 HF support is here, although I haven't tested it with all the different options.
